### PR TITLE
closes 8

### PR DESCRIPTION
**Pull request by jonathanbratt**
Updated the vignette to use the more streamlined version of `extract_features` from RBERT v. 0.1.9.

### CODE REVIEW

**Review by jonthegeek — CHANGES_REQUESTED** [review]
tests/testthat/RBERT_data.R should also be updated.

**Comment by jonathanbratt** [comment]
ok, sure, may as well.

**Comment by jonathanbratt** [comment]
this PR closes #8

**Review by jonthegeek — APPROVED** [review]

**Comment by jonthegeek** [comment]
Can you maybe kick appveyor to run again? If that doesn't fix it... kill the requirement, I guess?

**Pull request merged**
